use noet_ai::{
    AgendaDraft, AgendaItem, AgendaSection, AiResult, AiUsage, EmbeddingRequest, EmbeddingResponse,
    EmbeddingRuntime, EmbeddingVector, LabelSuggestion, LocalModelSpec, LocalRuntimeSettings,
    NoteReview, ReviewFinding, ReviewFindingKind, StructuredRequest, StructuredResponse,
    StructuredRuntime, StructuredTask, TaskExtraction,
};
use noet_app::AiSettings;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

pub(crate) struct PreviewAiRuntime;

impl StructuredRuntime for PreviewAiRuntime {
    fn complete_structured<T>(&self, request: StructuredRequest) -> AiResult<StructuredResponse<T>>
    where
        T: for<'de> serde::Deserialize<'de> + serde::Serialize,
    {
        let value = match request.task {
            StructuredTask::DraftOneOnOneAgenda => serde_json::to_value(AgendaDraft {
                person: person_from_agenda_instructions(&request.instructions),
                sections: vec![AgendaSection {
                    title: "Suggested agenda".into(),
                    items: request
                        .context
                        .iter()
                        .take(5)
                        .map(|block| AgendaItem {
                            text: block
                                .title
                                .clone()
                                .unwrap_or_else(|| "Review source context".into()),
                            sources: vec![block.source.clone()],
                        })
                        .collect(),
                }],
            }),
            StructuredTask::ReviewNote => serde_json::to_value(NoteReview {
                findings: vec![ReviewFinding {
                    kind: ReviewFindingKind::OpenQuestion,
                    text: "Review this note for decisions, risks, commitments, and missing task ownership.".into(),
                    sources: request
                        .context
                        .first()
                        .map(|block| vec![block.source.clone()])
                        .unwrap_or_default(),
                }],
                label_suggestions: vec![LabelSuggestion {
                    label: "review".into(),
                    reason: "Generated by local preview review action.".into(),
                    sources: request
                        .context
                        .first()
                        .map(|block| vec![block.source.clone()])
                        .unwrap_or_default(),
                }],
                task_extractions: request
                    .context
                    .first()
                    .map(|block| {
                        vec![TaskExtraction {
                            text: "Review extracted follow-ups".into(),
                            person: None,
                            due: None,
                            labels: vec!["followup".into()],
                            source: block.source.clone(),
                        }]
                    })
                    .unwrap_or_default(),
            }),
            _ => serde_json::to_value(NoteReview {
                findings: Vec::new(),
                label_suggestions: Vec::new(),
                task_extractions: Vec::new(),
            }),
        }
        .map_err(|err| noet_ai::AiRuntimeError::StructuredOutputFailed {
            message: err.to_string(),
        })?;
        let value = serde_json::from_value(value).map_err(|err| {
            noet_ai::AiRuntimeError::StructuredOutputFailed {
                message: err.to_string(),
            }
        })?;
        Ok(StructuredResponse {
            value,
            usage: Some(AiUsage {
                input_tokens: None,
                output_tokens: None,
            }),
        })
    }
}

pub(crate) struct PreviewEmbeddingRuntime;

impl EmbeddingRuntime for PreviewEmbeddingRuntime {
    fn embed(&self, request: EmbeddingRequest) -> AiResult<EmbeddingResponse> {
        Ok(EmbeddingResponse {
            vectors: request
                .inputs
                .into_iter()
                .map(|input| EmbeddingVector {
                    id: input.id,
                    values: preview_embedding(&input.text),
                })
                .collect(),
            usage: Some(AiUsage {
                input_tokens: None,
                output_tokens: None,
            }),
        })
    }
}

pub(crate) fn local_runtime_settings(settings: &AiSettings) -> LocalRuntimeSettings {
    let model_root = settings.model_root.clone();
    let timeout_seconds = settings.timeout_seconds;
    let mut runtime_settings = LocalRuntimeSettings::embedded();
    runtime_settings.models = local_model_specs(Path::new(&model_root));
    runtime_settings.timeout_seconds = timeout_seconds;
    runtime_settings
}

pub(crate) fn use_preview_ai_runtime() -> bool {
    match std::env::var("NOET_AI_RUNTIME") {
        Ok(value) if value.eq_ignore_ascii_case("local") => false,
        Ok(value) if value.eq_ignore_ascii_case("preview") => true,
        _ => cfg!(test),
    }
}

pub(crate) fn local_model_specs(model_root: &Path) -> BTreeMap<String, LocalModelSpec> {
    [
        (
            "mistral-7b-instruct-v0-3-gguf-q4-k-m",
            "bartowski",
            "Mistral-7B-Instruct-v0.3-GGUF",
            "Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
        ),
        (
            "ministral-8b-instruct-2410-gguf-q4-k-m",
            "bartowski",
            "Ministral-8B-Instruct-2410-GGUF",
            "Ministral-8B-Instruct-2410-Q4_K_M.gguf",
        ),
        (
            "mistral-nemo-instruct-2407-gguf-q4-k-m",
            "bartowski",
            "Mistral-Nemo-Instruct-2407-GGUF",
            "Mistral-Nemo-Instruct-2407-Q4_K_M.gguf",
        ),
    ]
    .into_iter()
    .map(|(profile, owner, repo, file)| {
        (
            profile.to_string(),
            LocalModelSpec {
                model_dir: resolve_model_dir(model_root, owner, repo, file),
                quantized_file: file.to_string(),
            },
        )
    })
    .collect()
}

pub(crate) fn require_free_memory(min_percent: u8) -> Result<(), String> {
    match current_free_memory_percent() {
        Some(free) if free < min_percent => Err(format!(
            "AI memory preflight failed: {free}% free, requires {min_percent}%"
        )),
        _ => Ok(()),
    }
}

fn preview_embedding(text: &str) -> Vec<f32> {
    let lower = text.to_lowercase();
    let launch = if lower.contains("launch") { 1.0 } else { 0.0 };
    let budget = if lower.contains("budget") { 1.0 } else { 0.0 };
    let followup = if lower.contains("follow") || lower.contains("task") {
        1.0
    } else {
        0.0
    };
    let meeting = if lower.contains("meeting") || lower.contains("agenda") {
        1.0
    } else {
        0.0
    };
    vec![launch, budget, followup, meeting]
}

fn resolve_model_dir(model_root: &Path, owner: &str, repo: &str, file: &str) -> PathBuf {
    let direct = model_root.join(file);
    if direct.exists() {
        return model_root.to_path_buf();
    }
    let repo_dir = model_root.join(owner).join(repo);
    if repo_dir.join(file).exists() {
        return repo_dir;
    }
    let hf_repo = model_root
        .join(format!("models--{owner}--{repo}"))
        .join("snapshots");
    if let Ok(snapshots) = std::fs::read_dir(&hf_repo) {
        for snapshot in snapshots.flatten() {
            let dir = snapshot.path();
            if dir.join(file).exists() {
                return dir;
            }
        }
    }
    model_root.join(format!("models--{owner}--{repo}"))
}

#[cfg(target_os = "macos")]
fn current_free_memory_percent() -> Option<u8> {
    let output = Command::new("memory_pressure").output().ok()?;
    let text = String::from_utf8_lossy(&output.stdout);
    text.lines().find_map(|line| {
        line.split_once("System-wide memory free percentage: ")
            .and_then(|(_, value)| value.trim().trim_end_matches('%').parse::<u8>().ok())
    })
}

#[cfg(not(target_os = "macos"))]
fn current_free_memory_percent() -> Option<u8> {
    None
}

fn person_from_agenda_instructions(instructions: &str) -> String {
    instructions
        .strip_prefix("Draft a concise, source-linked 1:1 agenda for ")
        .and_then(|rest| rest.split('.').next())
        .map(str::trim)
        .filter(|person| !person.is_empty())
        .unwrap_or("Selected person")
        .to_string()
}
