#!/usr/bin/env python3
"""Generate THIRD_PARTY_LICENSES.md for Noet.

Walks the full Cargo dependency graph (`cargo metadata`), lists every
third-party component with its version, SPDX license, and repository, then
collects the *actual* license texts from each crate's source tree (LICENSE /
COPYING / NOTICE files), de-duplicated by content. No network, no extra cargo
subcommands — just metadata + the already-vendored crate sources.

Run from the repo root:  python3 scripts/gen-licenses.py
Writes: crates/gui/src/third_party_licenses.md  (embedded by the GUI About view)
"""
import hashlib
import json
import os
import re
import subprocess
import sys

OUT = "crates/gui/src/third_party_licenses.md"
TSV = "crates/gui/src/third_party_components.tsv"  # name\tversion\tlicense  (in-app list)

# Vendored (non-crate) assets bundled in the repo — not in `cargo metadata`, so
# tracked explicitly here: (name, version, SPDX, repo, verbatim-license-path).
VENDORED_ASSETS = [
    ("lucide (SVG icons)", "—", "ISC", "https://lucide.dev",
     "crates/gui/ui/icons/LICENSE-lucide.txt"),
]
# Our own crates — not "third party".
OWN = {"noet-core", "noet-gui"}
LICENSE_FILE_RE = re.compile(r"^(LICENSE|LICENCE|COPYING|NOTICE|UNLICENSE)", re.IGNORECASE)


def metadata():
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],
        capture_output=True, text=True, check=True,
    ).stdout
    return json.loads(out)


def license_texts(pkg_dir):
    """Return [(filename, text)] for license-ish files directly in pkg_dir."""
    found = []
    try:
        for name in sorted(os.listdir(pkg_dir)):
            if LICENSE_FILE_RE.match(name):
                p = os.path.join(pkg_dir, name)
                if os.path.isfile(p):
                    try:
                        with open(p, encoding="utf-8", errors="replace") as f:
                            found.append((name, f.read().strip()))
                    except OSError:
                        pass
    except OSError:
        pass
    return found


def main():
    m = metadata()
    pkgs = [p for p in m["packages"] if p["name"] not in OWN]
    pkgs.sort(key=lambda p: (p["name"].lower(), p["version"]))

    # Component table rows + collect distinct license texts (hash -> (text, crates)).
    texts = {}
    rows = []
    unknown = []
    for p in pkgs:
        lic = p.get("license") or (p.get("license_file") and "see license file") or "UNKNOWN"
        if lic == "UNKNOWN":
            unknown.append(f'{p["name"]} {p["version"]}')
        repo = p.get("repository") or ""
        rows.append((p["name"], p["version"], lic, repo))
        pkg_dir = os.path.dirname(p["manifest_path"])
        for _name, text in license_texts(pkg_dir):
            if not text:
                continue
            h = hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()
            entry = texts.setdefault(h, {"text": text, "crates": set()})
            entry["crates"].add(f'{p["name"]} {p["version"]}')

    # Vendored non-crate assets (bundled SVG icons, etc.).
    for name, ver, lic, repo, lic_path in VENDORED_ASSETS:
        rows.append((name, ver, lic, repo))
        try:
            with open(lic_path, encoding="utf-8") as fh:
                text = fh.read().strip()
            h = hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()
            entry = texts.setdefault(h, {"text": text, "crates": set()})
            entry["crates"].add(f"{name} {ver}")
        except OSError:
            unknown.append(f"{name} (missing {lic_path})")

    lines = []
    lines.append("# Third-party open-source licenses")
    lines.append("")
    lines.append(
        "Noet bundles the third-party Rust crates listed below. This file is "
        "generated by `scripts/gen-licenses.py` from `cargo metadata` and the "
        "crates' own license files; regenerate it when dependencies change."
    )
    lines.append("")
    lines.append("## Slint (the UI toolkit)")
    lines.append("")
    lines.append(
        "Noet's GUI is built with **Slint**, which is tri-licensed: "
        "**GPL-3.0-only**, a paid **commercial** license, or the "
        "**Slint Royalty-free 2.0** / **Slint Software 3.0** licenses. Confirm "
        "which license you ship Noet under and include Slint's required notice; "
        "see https://slint.dev/ and the Slint crates listed below."
    )
    lines.append("")
    if unknown:
        lines.append("## ⚠ Components with no SPDX license in metadata")
        lines.append("")
        lines.append(
            "These need manual review (check the crate's repository for terms):"
        )
        lines.append("")
        for u in unknown:
            lines.append(f"- {u}")
        lines.append("")
    lines.append(f"## Components ({len(rows)})")
    lines.append("")
    lines.append("| Crate | Version | License | Source |")
    lines.append("|-------|---------|---------|--------|")
    for name, ver, lic, repo in rows:
        lines.append(f"| {name} | {ver} | {lic} | {repo} |")
    lines.append("")
    lines.append(f"## License texts ({len(texts)} distinct)")
    lines.append("")
    for h, entry in sorted(texts.items(), key=lambda kv: sorted(kv[1]["crates"])[0].lower()):
        crates = ", ".join(sorted(entry["crates"]))
        lines.append(f"### Used by: {crates}")
        lines.append("")
        lines.append("```")
        lines.append(entry["text"])
        lines.append("```")
        lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    # Compact tab-separated list for the in-app (virtualized) component view.
    with open(TSV, "w", encoding="utf-8") as f:
        for name, ver, lic, _repo in rows:
            f.write(f"{name}\t{ver}\t{lic}\n")

    print(f"wrote {OUT} ({len(rows)} components, {len(texts)} license texts) and {TSV}", file=sys.stderr)


if __name__ == "__main__":
    main()
